# Tensors

In [75]:
import torch
print(torch.__version__)

2.9.1


In [76]:
if torch.cuda.is_available():
    print('GPU is Available')
else:
    print('Not Available, using CPU')

Not Available, using CPU


## Creating a Tensor

In [77]:
#using empty
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [78]:
#using zeroes
torch.zeros(5,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [79]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [80]:
#using rand
torch.rand(2,2)

tensor([[0.9122, 0.8493],
        [0.6292, 0.4086]])

In [81]:
#using seed
torch.manual_seed(50)
torch.rand(2,2)

tensor([[0.6180, 0.0687],
        [0.3893, 0.0404]])

In [82]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [83]:
#other ways
torch.arange(1,100,3)

tensor([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52,
        55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [84]:
torch.linspace(1,10,4)

tensor([ 1.,  4.,  7., 10.])

In [85]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [86]:
torch.full((3,3), 2)

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

In [87]:
x = torch.tensor([[1,2,3], [4,5,6]])
x.shape

torch.Size([2, 3])

In [88]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [89]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.4013, 0.1442, 0.4605],
        [0.4877, 0.5927, 0.9634]])

## Mathematical Operations

### Scaler

In [90]:
x = torch.rand(2,2)
x

tensor([[0.1230, 0.4048],
        [0.4985, 0.9987]])

In [91]:
# Scaler operations

## ADD
a = x+2

## SUBTRACT
sub = x*2
sub

#similar for multiply, divide, power, mod

tensor([[0.2460, 0.8095],
        [0.9970, 1.9975]])

### Element-wise

In [92]:
b = torch.rand_like(x, dtype=torch.float32)

In [93]:
a + b

tensor([[2.7279, 2.9277],
        [3.1959, 3.2492]])

In [94]:
a-b

tensor([[1.5181, 1.8819],
        [1.8011, 2.7482]])

In [95]:
a*b

tensor([[1.2841, 1.2575],
        [1.7424, 0.7512]])

In [96]:
a/b

tensor([[ 3.5099,  4.5989],
        [ 3.5826, 11.9705]])

In [97]:
torch.log(c)

tensor([[-inf, 0.],
        [0., 0.]])

In [98]:
torch.sqrt(c)

tensor([[0., 1.],
        [1., 1.]])

In [99]:
torch.exp(c)

tensor([[1.0000, 2.7183],
        [2.7183, 2.7183]])

In [100]:
torch.sigmoid(c)

tensor([[0.5000, 0.7311],
        [0.7311, 0.7311]])

In [101]:
torch.sigmoid(c)

tensor([[0.5000, 0.7311],
        [0.7311, 0.7311]])

In [102]:
torch.softmax(c, dim=0)

tensor([[0.2689, 0.5000],
        [0.7311, 0.5000]])

In [103]:
torch.relu(c)

tensor([[0., 1.],
        [1., 1.]])

In [104]:
a.add_(c)

tensor([[2.1230, 3.4048],
        [3.4985, 3.9987]])

In [105]:
d = c.clone()

In [106]:
# PERMUTE

b = torch.rand(5,3,4)
b.permute(1,0,2)

tensor([[[0.3624, 0.4621, 0.7145, 0.5058],
         [0.3490, 0.1953, 0.2792, 0.2526],
         [0.1705, 0.2914, 0.5682, 0.0380],
         [0.4388, 0.4589, 0.0359, 0.3525],
         [0.2074, 0.4779, 0.4203, 0.4014]],

        [[0.0518, 0.2492, 0.2395, 0.4233],
         [0.3792, 0.7686, 0.6907, 0.7526],
         [0.2715, 0.6987, 0.0944, 0.6719],
         [0.0389, 0.3880, 0.1319, 0.5018],
         [0.0436, 0.6490, 0.9007, 0.8274]],

        [[0.0022, 0.6848, 0.7497, 0.2489],
         [0.1184, 0.8699, 0.8391, 0.0532],
         [0.3782, 0.8738, 0.7267, 0.9486],
         [0.8077, 0.9322, 0.5680, 0.5034],
         [0.3785, 0.7518, 0.2839, 0.7220]]])