## Creating NumPY Arrays

-Creating arrays
-Creating Zeroes Matrix/Vector
-Creating All ones Matrix
-Creating Identity Matrix
-Creating Linearly Spaces Vector

In [22]:
import numpy as np

In [23]:
# Creating a 2D NumPy array
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
# Creating a 2x3 array of zeroes
arr_zeroes = np.zeros((2,3))
arr_zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# Creating a 4x4 array of ones
arr_ones = np.ones((4,4))
arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
# Creating a 5x5 identity matrix
arr_identify = np.identity(5)
arr_identify

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
#Creating an array with a range of values
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
#creating an array with a specific start, stop and step values

arr3 = np.arange(5, 15, 2)
arr3

array([ 5,  7,  9, 11, 13])

In [29]:
# Creating an array with linearly spaced values
arr4 = np.linspace(10, 100, 10)
arr4

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Important Attributes
Shape

In [21]:
arr_ones.shape

(4, 4)

In [39]:
arr5 = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
arr5

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [40]:
arr5.ndim

3

In [41]:
arr5.size

8

In [43]:
arr5.dtype

dtype('int64')

In [44]:
arr5.astype(np.float64)

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

## NumPy Lists vs Python List Efficiency

In [53]:
lista = list(range(100))
arraya = np.arange(100)

In [ ]:
import sys


In [58]:
print(sys.getsizeof(lista)) 
print(sum(sys.getsizeof(x) for x in lista)) 

#For Arrays
print('Arrays')
print(arraya.nbytes) 
print(sys.getsizeof(arraya))

856
2796
Arrays
800
912


In [59]:
import time

In [61]:
x = range(10)
y = range(1000000, 2000000)

In [64]:
for i in x:
    print(i)

0
1
2
3
4
5
6
7
8
9
